### ISSUE TITLE
Why not Task?

### ISSUE THREAD

**Issue by ArchiDog1998** [NightmareXIV/ECommons#18]
https://github.com/NightmareXIV/ECommons/blob/c70f1231fa1649792c9243ef499fb0ec34485148/ECommons/ImGuiMethods/ThreadLoadImageHandler.cs#L69

I have a question about this line. Why there is a thread instead of a task? As far as I know, the task may be faster. I am not good at this.

**Comment by Limiana** [comment]
You could use task but task thread pool is shared between all plugins and if there's a lot of tasks next tasks could be delayed.. and I was told back then that thread is better for things that may take a while to run and this one definitely can take some time

**Comment by ArchiDog1998** [comment]
Oh, I see. Thanks for your reply!
