### ISSUE TITLE
`DalamudReflector.RegisterOnInstalledPluginsChangedEvents` not triggering

### ISSUE THREAD

**Issue by zbee** [NightmareXIV/ECommons#29]
The method does not appear to run at any time, the log message that the event was fired never shows - no error, just never runs.

**Comment by Limiana** [comment]
Hello! I'll check it in a bit

**Comment by Limiana** [comment]
Hello! Just giving an update on it, unfortunately this is issue on Dalamud's side, ActivePluginsChange event simply doesn't works

**Comment by zbee** [comment]
Did you have a chance to put in a bug for it, or can you link it? I'm not sure where I would submit that

**Comment by Limiana** [comment]
> Did you have a chance to put in an issue for it? I'm not sure where I would submit that

Not yet, but I have implemented workaround now and it seems to work fine. Please try it in the latest version and let me know

**Comment by Limiana** [comment]
I believe this issue is resolved now, I'm going to close and if there is still an issue please reopen it
