### ISSUE TITLE
Don't obsolete ProperOnLogin.Unregister

### ISSUE THREAD

**Issue by Jaksuhn** [NightmareXIV/ECommons#65]
https://github.com/NightmareXIV/ECommons/blob/724e3d014f2f577e4d2faf9943fd189377e1cbee/ECommons/Events/ProperOnLogin.cs#L82-L93

While it's true and good that it disposes with ecommons itself, it's sometimes intended to be manually unregistered without the plugin itself unloading, in the case of tweaks within a plugin that utilise this that could be disabled at any time irrespective of the main plugin.

**Comment by Limiana** [comment]
I think this was done already
